"""Strict public-interface tests for evidence-driven wave replanning."""

import copy
import importlib.util
import json
import socket
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock


# The verifier is loaded from its checked-in path; keep that source tree free of
# generated bytecode during contract tests and checklist replays.
sys.dont_write_bytecode = True


ROOT = Path(__file__).resolve().parents[1]
VERIFIER = ROOT / "skills" / "replan" / "scripts" / "verify_replan.py"
INPUT_TEMPLATE = ROOT / "skills" / "replan" / "templates" / "REPLAN_INPUT.template.json"
RESULT_TEMPLATE = ROOT / "skills" / "replan" / "templates" / "REPLAN_RESULT.template.json"


def load_verifier():
    spec = importlib.util.spec_from_file_location("verify_replan", VERIFIER)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def current_plan():
    return {
        "schema_version": 1,
        "epic": {
            "title": "Iterative planning",
            "spec_path": "DESIGN_SPEC.md",
            "intent_and_why": "Plan from evidence at wave boundaries.",
        },
        "definition_of_done": ["The epic outcome is demonstrated."],
        "good_enough": {
            "mandatory_quality": "Strict contracts",
            "sufficient_evidence": "Public-interface tests",
            "appetite": "One bounded wave",
        },
        "hard_constraints": ["No network writes"],
        "fixed_decisions": ["Launched identities remain stable"],
        "current_wave": {
            "objective": "Validate the replanning seam",
            "exit_criteria": ["All four exits verify"],
            "issues": [issue("A")],
        },
        "wave_forecast": [forecast()],
        "uncertainty_register": [uncertainty()],
        "parked_possibilities": ["Portfolio optimization"],
    }


def issue(issue_id="A"):
    return {
        "id": issue_id,
        "title": f"Issue {issue_id}",
        "desired_outcome": "Observable wave evidence exists.",
        "useful_now": "It settles the current decision.",
        "appetite": "One gate",
        "acceptance_or_falsification_evidence": "The verifier passes or refuses.",
        "implementation_latitude": "Choose internals; preserve fixed boundaries.",
        "hard_constraints_no_gos": [],
        "local_unknowns": [],
        "anchors": ["skills/replan"],
        "type": "AFK",
        "blocks": [],
    }


def forecast():
    return {"outcome": "Wire role contracts", "why_likely": "The seam is accepted", "entry_conditions": []}


def uncertainty():
    return {
        "unknown": "Which next wave is useful",
        "affects": "Forecast ordering",
        "settle_by": "Wave review",
        "current_evidence": "Only the initial wave has run",
        "next_probe": "Inspect completed outcomes",
    }


CLASSIFICATIONS = [
    "blocks_current_wave_exit",
    "invalidates_forecast_or_decomposition",
    "later_only",
    "evidence_only",
    "drop",
]
ACTIONS = [
    "repair_current_wave",
    "revise_plan",
    "amend_forecast_or_parked",
    "record_evidence_only",
    "drop",
]


def replan_input(*, open_ids=None):
    discrepancies = []
    for index, classification in enumerate(CLASSIFICATIONS):
        discrepancies.append({
            "id": f"D{index}",
            "signal": f"Signal {index}",
            "classification": classification,
            "affects": "Current planning truth",
            "evidence": "Observed during the wave",
            "reason": "Deliberately dropped" if classification == "drop" else "Disposition is evidence-led",
        })
    open_ids = ["A"] if open_ids is None else open_ids
    completed = [] if open_ids else [{"issue_id": "A", "outcome": "Done", "evidence": "Test output"}]
    return {
        "schema_version": 1,
        "current_plan": current_plan(),
        "completed_outcomes": completed,
        "wave_evidence": [
            {"claim": "The seam is usable", "expected": "All exits verify", "observed": "Checks pass", "source": "tests"}
        ],
        "discrepancies": discrepancies,
        "open_current_wave_issue_ids": open_ids,
        "unlaunched_items": [
            {"id": "U-issue", "kind": "issue"},
            {"id": "U-forecast", "kind": "forecast"},
            {"id": "U-uncertainty", "kind": "uncertainty"},
            {"id": "U-parked", "kind": "parked"},
        ],
        "repo_state": {"anchors": ["skills/replan"], "map_status": "No architecture map"},
    }


def replan_result(decision="repair", *, source=None):
    source = source or replan_input()
    dispositions = []
    for discrepancy, action in zip(source["discrepancies"], ACTIONS):
        dispositions.append({
            "id": discrepancy["id"],
            "action": action,
            "reason": "Evidence supports this disposition",
            "issue_created": action not in {"record_evidence_only", "drop"},
        })
    return {
        "schema_version": 1,
        "decision": decision,
        "applicable": True,
        "criteria_assessment": {
            "wave_exit": "Current exit criteria remain measurable.",
            "epic_done": "The epic is not complete.",
            "good_enough": "The mandatory quality boundary is preserved.",
        },
        "discrepancy_dispositions": dispositions,
        "current_wave": copy.deepcopy(source["current_plan"]["current_wave"]),
        "revised_forecast": copy.deepcopy(source["current_plan"]["wave_forecast"]),
        "revised_uncertainty": copy.deepcopy(source["current_plan"]["uncertainty_register"]),
        "revised_parked": copy.deepcopy(source["current_plan"]["parked_possibilities"]),
        "unlaunched_dispositions": [
            {"id": item["id"], "action": "keep", "reason": "Still supported"}
            for item in source["unlaunched_items"]
        ],
        "material_changes": [],
        "wave_review_comment": "## Wave review\n\nEvidence was classified and every item was dispositioned.",
        "revised_epic_body": "## Current planning truth\n\nThe current wave and nonbinding forecast are explicit.",
        "escalation": None,
    }


class MissingBehaviorTest(unittest.TestCase):
    def test_replan_public_behavior_exists(self):
        self.assertTrue(
            VERIFIER.is_file() and INPUT_TEMPLATE.is_file() and RESULT_TEMPLATE.is_file(),
            "missing replanning behavior: strict verifier/renderer and v1 templates are not minted",
        )


@unittest.skipUnless(VERIFIER.is_file(), "awaiting the test-led replan implementation")
class ReplanContractTests(unittest.TestCase):
    def setUp(self):
        self.replan = load_verifier()

    def test_checked_in_templates_are_directly_valid(self):
        source = json.loads(INPUT_TEMPLATE.read_text(encoding="utf-8"))
        result = json.loads(RESULT_TEMPLATE.read_text(encoding="utf-8"))
        self.replan.verify_replan_input(source)
        self.replan.verify_replan_result(source, result)

    def test_all_four_exit_decisions_verify(self):
        for decision in ("advance", "repair", "replan", "stop"):
            with self.subTest(decision=decision):
                source = replan_input()
                result = replan_result(decision, source=source)
                if decision == "stop":
                    result["current_wave"] = None
                self.replan.verify_replan_result(source, result)

    def test_repair_holds_current_wave_and_forecast(self):
        source = replan_input()
        for field, mutation in (
            ("current_wave", lambda value: value.__setitem__("objective", "Changed")),
            ("revised_forecast", lambda value: value.clear()),
        ):
            with self.subTest(field=field):
                result = replan_result("repair", source=source)
                mutation(result[field])
                with self.assertRaises(self.replan.ReplanError):
                    self.replan.verify_replan_result(source, result)

    def test_stop_alone_may_have_null_current_wave(self):
        for decision in ("advance", "repair", "replan"):
            result = replan_result(decision)
            result["current_wave"] = None
            with self.subTest(decision=decision), self.assertRaises(self.replan.ReplanError):
                self.replan.verify_replan_result(replan_input(), result)

    def test_discrepancy_dispositions_are_complete_unique_and_classification_matched(self):
        source = replan_input()
        mutations = [
            lambda result: result["discrepancy_dispositions"].pop(),
            lambda result: result["discrepancy_dispositions"].append(copy.deepcopy(result["discrepancy_dispositions"][0])),
            lambda result: result["discrepancy_dispositions"][0].__setitem__("action", "drop"),
        ]
        for mutate in mutations:
            result = replan_result(source=source)
            mutate(result)
            with self.subTest(mutate=mutate), self.assertRaises(self.replan.ReplanError):
                self.replan.verify_replan_result(source, result)

    def test_evidence_only_and_drop_never_claim_issue_creation(self):
        source = replan_input()
        for index in (3, 4):
            result = replan_result(source=source)
            result["discrepancy_dispositions"][index]["issue_created"] = True
            with self.subTest(index=index), self.assertRaises(self.replan.ReplanError):
                self.replan.verify_replan_result(source, result)

    def test_unlaunched_dispositions_are_complete_unique_and_replacement_is_discriminated(self):
        source = replan_input()
        result = replan_result(source=source)
        result["unlaunched_dispositions"].pop()
        with self.assertRaises(self.replan.ReplanError):
            self.replan.verify_replan_result(source, result)
        replacements = {
            "issue": issue("U-issue"),
            "forecast": forecast(),
            "uncertainty": uncertainty(),
            "parked": "A rewritten parked possibility",
        }
        for index, item in enumerate(source["unlaunched_items"]):
            valid = replan_result(source=source)
            valid["unlaunched_dispositions"][index].update(
                {"action": "rewrite", "replacement": copy.deepcopy(replacements[item["kind"]])}
            )
            self.replan.verify_replan_result(source, valid)
            invalid = copy.deepcopy(valid)
            invalid["unlaunched_dispositions"][index]["replacement"] = 42
            with self.subTest(kind=item["kind"]), self.assertRaises(self.replan.ReplanError):
                self.replan.verify_replan_result(source, invalid)

    def test_nonrewrite_disposition_must_not_carry_replacement(self):
        source = replan_input()
        result = replan_result(source=source)
        result["unlaunched_dispositions"][0]["replacement"] = issue("U-issue")
        with self.assertRaises(self.replan.ReplanError):
            self.replan.verify_replan_result(source, result)

    def test_launched_open_issue_identity_is_stable_when_applicable(self):
        source = replan_input()
        result = replan_result("advance", source=source)
        result["current_wave"]["issues"][0]["title"] = "Silently rewritten"
        with self.assertRaises(self.replan.ReplanError):
            self.replan.verify_replan_result(source, result)

    def test_input_identity_partition_and_strict_shape_fail_fast(self):
        mutations = [
            lambda value: value.__setitem__("schema_version", True),
            lambda value: value.__setitem__("unknown", True),
            lambda value: value.__setitem__("wave_evidence", []),
            lambda value: value["discrepancies"].append(copy.deepcopy(value["discrepancies"][0])),
            lambda value: value["open_current_wave_issue_ids"].append("missing"),
            lambda value: value["completed_outcomes"].append({"issue_id": "A", "outcome": "Done", "evidence": "e"}),
        ]
        for mutate in mutations:
            value = replan_input()
            mutate(value)
            with self.subTest(mutate=mutate), self.assertRaises(self.replan.ReplanError):
                self.replan.verify_replan_input(value)

    def test_each_fixed_boundary_has_typed_escalation_and_is_inapplicable(self):
        valid_values = {
            "intent_and_why": "A revised intent proposal",
            "definition_of_done": ["A revised completion proposal"],
            "good_enough": {"mandatory_quality": "M", "sufficient_evidence": "E", "appetite": "A"},
            "hard_constraints": [],
            "fixed_decisions": ["A revised decision proposal"],
        }
        for boundary, proposed in valid_values.items():
            source = replan_input()
            result = replan_result("replan", source=source)
            result["applicable"] = False
            result["material_changes"] = [
                {"surface": boundary, "before": "confirmed", "after": "proposed", "reason": "Evidence crossed the boundary"}
            ]
            result["escalation"] = {
                "boundary": boundary,
                "proposed_value": copy.deepcopy(proposed),
                "reason": "Human authority is required",
                "authority_required": "human",
            }
            self.replan.verify_replan_result(source, result)
            invalid = copy.deepcopy(result)
            invalid["escalation"]["proposed_value"] = 42
            with self.subTest(boundary=boundary), self.assertRaises(self.replan.ReplanError):
                self.replan.verify_replan_result(source, invalid)

    def test_fixed_change_cannot_be_applicable_or_lack_matching_escalation(self):
        source = replan_input()
        result = replan_result("replan", source=source)
        result["material_changes"] = [
            {"surface": "intent_and_why", "before": "old", "after": "new", "reason": "Observed delta"}
        ]
        for applicable, escalation in ((True, None), (False, None)):
            candidate = copy.deepcopy(result)
            candidate["applicable"] = applicable
            candidate["escalation"] = escalation
            with self.subTest(applicable=applicable), self.assertRaises(self.replan.ReplanError):
                self.replan.verify_replan_result(source, candidate)

    def test_singular_escalation_refuses_multiple_fixed_boundaries(self):
        source = replan_input()
        result = replan_result("replan", source=source)
        result["applicable"] = False
        result["material_changes"] = [
            {"surface": "intent_and_why", "before": "old", "after": "new", "reason": "Evidence"},
            {"surface": "fixed_decisions", "before": "old", "after": "new", "reason": "Evidence"},
        ]
        result["escalation"] = {
            "boundary": "intent_and_why",
            "proposed_value": "A revised intent",
            "reason": "Human decision required",
            "authority_required": "human",
        }
        with self.assertRaises(self.replan.ReplanError):
            self.replan.verify_replan_result(source, result)

    def test_unlaunched_issue_identity_cannot_collide_with_launched_issue(self):
        source = replan_input()
        source["unlaunched_items"][0]["id"] = "A"
        with self.assertRaises(self.replan.ReplanError):
            self.replan.verify_replan_input(source)

    def test_exact_g1_duplicate_string_values_are_preserved(self):
        source = replan_input()
        source["current_plan"]["parked_possibilities"] = ["same", "same"]
        result = replan_result("advance", source=source)
        result["revised_parked"] = ["same", "same"]
        self.replan.verify_replan_result(source, result)

        for boundary in ("definition_of_done", "hard_constraints", "fixed_decisions"):
            candidate = replan_result("replan", source=source)
            candidate["applicable"] = False
            candidate["material_changes"] = [
                {"surface": boundary, "before": "old", "after": "new", "reason": "Evidence"}
            ]
            candidate["escalation"] = {
                "boundary": boundary,
                "proposed_value": ["same", "same"],
                "reason": "Human decision required",
                "authority_required": "human",
            }
            with self.subTest(boundary=boundary):
                self.replan.verify_replan_result(source, candidate)

    def test_issue_rewrites_validate_in_the_assembled_result_graph(self):
        source = replan_input(open_ids=["A", "B"])
        source["current_plan"]["current_wave"]["issues"].append(issue("B"))

        valid = replan_result("replan", source=source)
        replacement = issue("U-issue")
        replacement["blocks"] = ["B"]
        valid["unlaunched_dispositions"][0].update(
            {"action": "rewrite", "replacement": replacement}
        )
        self.replan.verify_replan_result(source, valid)

        dangling = copy.deepcopy(valid)
        dangling["unlaunched_dispositions"][0]["replacement"]["blocks"] = ["missing"]
        with self.assertRaises(self.replan.ReplanError):
            self.replan.verify_replan_result(source, dangling)

        cyclic_source = copy.deepcopy(source)
        cyclic_source["unlaunched_items"].append({"id": "U-other", "kind": "issue"})
        cyclic = replan_result("replan", source=cyclic_source)
        first = issue("U-issue")
        first["blocks"] = ["U-other"]
        second = issue("U-other")
        second["blocks"] = ["U-issue"]
        cyclic["unlaunched_dispositions"][0].update({"action": "rewrite", "replacement": first})
        cyclic["unlaunched_dispositions"][-1].update({"action": "rewrite", "replacement": second})
        with self.assertRaises(self.replan.ReplanError):
            self.replan.verify_replan_result(cyclic_source, cyclic)

    def test_renderer_and_cli_are_offline_and_nonempty(self):
        source = replan_input()
        result = replan_result("replan", source=source)
        rendered = self.replan.render_replan_markdown(source, result)
        self.assertIn("## Wave decision", rendered)
        self.assertIn(result["wave_review_comment"], rendered)
        self.assertIn(result["revised_epic_body"], rendered)
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            input_path = root / "input.json"
            result_path = root / "result.json"
            input_path.write_text(json.dumps(source), encoding="utf-8")
            result_path.write_text(json.dumps(result), encoding="utf-8")
            with mock.patch.object(socket, "create_connection", side_effect=AssertionError("network")):
                self.assertEqual(0, self.replan.main([str(input_path), str(result_path)]))


if __name__ == "__main__":
    unittest.main()
