"""Variant rankings (can the centrality signal be rescued?) + the hole-priority artifact."""
import json
import random
from pathlib import Path

X4 = Path(r"C:\Programs\constellation-skills\.claude\worktrees\explore-code-map\.agent-work\explore-code-map\evidence\x4")

rows = json.loads((X4 / "centrality_scored.json").read_text(encoding="utf-8"))


def is_private(r):
    return any(p.startswith("_") and not p.startswith("__") for p in r["qual"].split("."))


def report(name, pool, key):
    ranked = sorted(pool, key=key)
    n = len(pool)
    base = sum(r["leaf_hit"] for r in pool) / n if n else 0
    out = [f"\n=== {name} ===  population={n}  base={base:.1%}"]
    for K in (10, 20, 30):
        top = ranked[:K]
        h = sum(r["leaf_hit"] for r in top)
        lift = (h / K / base) if base else float("nan")
        out.append(f"{K:>5} {h:>3} hits {h/K:>7.1%}  lift={lift:>5.2f}x")
    print("\n".join(out))
    return ranked, base


pub = [r for r in rows if not is_private(r)]
priv_frac_30 = sum(is_private(r) for r in sorted(rows, key=lambda r: -r["pagerank"])[:30]) / 30
print(f"private (underscore-prefixed) share of top-30 PageRank: {priv_frac_30:.0%}")
print(f"private share of whole population: {sum(is_private(r) for r in rows)/len(rows):.0%}")

report("PageRank, ALL", rows, lambda r: -r["pagerank"])
report("PageRank, PUBLIC only", pub, lambda r: -r["pagerank"])
report("in-degree, PUBLIC only", pub, lambda r: -r["in_degree"])
report("in-weight, PUBLIC only", pub, lambda r: -r["in_weight"])
classes = [r for r in rows if r["kind"] == "type"]
report("PageRank, CLASSES only", classes, lambda r: -r["pagerank"])

random.seed(1)
pubn = len(pub); pubbase = sum(r["leaf_hit"] for r in pub) / pubn
t = sorted(sum(r["leaf_hit"] for r in random.sample(pub, 30)) / 30 for _ in range(2000))
print(f"\nrandom 30-draw from PUBLIC pool: mean={sum(t)/len(t):.1%} p95={t[int(.95*len(t))]:.1%} max={t[-1]:.1%}")

# ---------------- the artifact: ranked hole list ----------------
# Primary ordering uses in-weight (total internal call count), the only signal that
# beat the random baseline against the curated map (p=0.0005 at K=30). PageRank is
# carried as a column, not as the ordering, because it did not validate.
for i, r in enumerate(sorted(rows, key=lambda r: (-r["in_weight"], -r["in_degree"])), 1):
    r["iw_rank"] = i
holes_all = [r for r in sorted(rows, key=lambda r: -r["pagerank"]) if not r["has_docstring"]]
holes_pub = [r for r in sorted(pub, key=lambda r: (-r["in_weight"], -r["in_degree"])) if not r["has_docstring"]]
for i, r in enumerate(holes_all, 1):
    r["hole_rank_all"] = i
for i, r in enumerate(holes_pub, 1):
    r["hole_rank_pub"] = i

print(f"\nholes: {len(holes_all)} of {len(rows)} graph entities have no docstring "
      f"({len(holes_all)/len(rows):.0%}); public holes: {len(holes_pub)} of {len(pub)} ({len(holes_pub)/len(pub):.0%})")


def table(hs, limit=None, primary="in-weight"):
    lines = [f"| # | entity | calls in | callers | PageRank rank | named by map? | file:line |",
             "|---:|---|---:|---:|---:|:--:|---|"]
    for i, r in enumerate(hs[:limit] if limit else hs, 1):
        loc = f"`{r['file']}:{r['line']}`" if r["line"] else f"`{r['file']}`"
        lines.append(f"| {i} | `{r['module']}.{r['qual']}` | {r['in_weight']} | {r['in_degree']} | "
                     f"{r['pr_rank']} | {'yes' if r['leaf_hit'] else 'no'} | {loc} |")
    return "\n".join(lines)


doc = [
    "# f1Brainz — ranked docstring-hole priority list",
    "",
    "Generated by excursion x4 (`variants_and_holes.py`). Source graph: symbol-level call",
    "graph decoded from the SCIP index built by excursion x1 (`evidence/x1/call_edges.jsonl`),",
    "restricted to f1Brainz's own `src/` definitions: 4217 nodes, 4465 internal edges.",
    "\"Hole\" = the entity has no docstring, verified by AST parse of the live source rather",
    "than trusting the SCIP flag.",
    "",
    "## How this is ordered, and why not by PageRank",
    "",
    "x4 measured each candidate signal against the entities f1Brainz's own curated map",
    "(`docs/architecture/`) chose to name. **PageRank did not beat a random draw** at any K",
    "(p >= 0.17; top-10 lift 0.87x). It promotes widely-called private micro-helpers —",
    f"{priv_frac_30:.0%} of its top 30 are underscore-prefixed — which is exactly the class of",
    "entity an architecture map deliberately omits.",
    "",
    "**In-weight (total internal call count) did validate**: 60% of its top 10 and 47% of its",
    "top 30 are entities the curated map names, against a 19.4% base rate (p=0.005 and",
    "p=0.0005). So this list is ordered by in-weight over public entities, and carries the",
    "PageRank rank as a column for comparison rather than as the ordering.",
    "",
    "Treat it as a prioritized worklist, not an oracle: a validated 2.4x lift still means",
    "roughly half the top entries are things the map felt no need to name.",
    "",
    f"## A. Public entities with no docstring, by call count ({len(holes_pub)} total)",
    "",
    table(holes_pub, 60),
    "",
    f"_(showing top 60 of {len(holes_pub)}; full data in `centrality_scored.json`)_",
    "",
    f"## B. All entities incl. private, ordered by PageRank ({len(holes_all)} total)",
    "",
    "Retained as the disconfirming exhibit — this is the ordering the exploration expected",
    "to work, and the private-helper pollution is visible from the first rows.",
    "",
    table(holes_all, 40),
    "",
    f"_(showing top 40 of {len(holes_all)})_",
    "",
]
(X4 / "hole_priority_list.md").write_text("\n".join(doc), encoding="utf-8")
print("\nwrote hole_priority_list.md")
print("\nTOP 15 PUBLIC HOLES")
for r in holes_pub[:15]:
    print(f"  PRrank={r['pr_rank']:4d} in={r['in_degree']:3d} map={'Y' if r['leaf_hit'] else 'n'} "
          f"{r['module']}.{r['qual']}  ({r['file']}:{r['line']})")
