#!/usr/bin/env python
"""Two-arm live-fire acceptance harness for issue #440.

Answers ONE question with evidence:

    Does a HARD governor trip fire from a per-agent gauge reading produced by
    an agent that was dispatched into a worktree?

Not "does the path resolve" -- a fired trip, observed, on a live headless run,
with a byte-identical control arm.

WHY A SANDBOX PAIR AND NOT AN IN-PLACE TEST
-------------------------------------------
Hook code is not fenced by worktree isolation. `CLAUDE_PROJECT_DIR` resolves
once at session launch (#269) and is inherited unchanged by every subagent, so
an agent dispatched into a worktree still executes the MAIN CHECKOUT's hook code
against the MAIN CHECKOUT's state. The mechanism under repair is therefore the
mechanism that would make an in-worktree validation lie.

So each arm is a DISPOSABLE SANDBOX PAIR under a temp directory:

  * sandbox main  -- a scratch `git init` repo standing in for a main checkout.
  * sandbox wt    -- a real `git worktree add` of that repo.

and the arm's hooks are wired BY ABSOLUTE PATH into an arm-private `scripts/`
tree. The headless session is launched with cwd AND `CLAUDE_PROJECT_DIR` set to
the sandbox main -- which is the defect's own precondition -- while the spine it
drives lives in the sandbox worktree.

THE ONLY DIFFERENCE BETWEEN THE TWO ARMS IS WHICH ARM DIRECTORY THE ABSOLUTE
HOOK PATH POINTS AT. Sandbox, prompt, models, spine, filler and command sequence
are generated by the same code for both.

NOTHING IS HAND-INJECTED. The harness never places the sandbox worktree root
into a hook payload field, a fixture, or an environment variable that the hook
reads back. The spine is created in the worktree; the hook must find it.

Usage:
    python run_two_arm.py              # probe, build, run both arms, collect, clean
    python run_two_arm.py --keep       # same but leave the temp tree in place
    python run_two_arm.py --probe-only
    python run_two_arm.py --arm treatment
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
EVIDENCE = HERE / "evidence"
REPO = HERE.parents[2]          # <worktree>/.agent-work/issue-440-binding-cwd/acceptance -> <worktree>
TMP = Path(os.environ.get("ACC440_TMP") or (Path(os.environ["TEMP"]) / "acc440"))

CLAUDE = Path(r"C:\Users\fredc\.local\bin\claude.exe")

# The commit the fix sits on top of; the control arm's scripts/ tree.
BASE_COMMIT = "cbd9aee"

# Parent runs one model, the dispatched subagent another, so gauge.json's own
# `model` field names WHICH of the two produced the reading (attribution #3).
PARENT_MODEL = "opus"
SUBAGENT_MODEL = "sonnet"
SUBAGENT_MODEL_ID = "claude-sonnet-5"   # what gauge.json should carry

WORK_ID = "sbwork"
ENGINE_SESSION = "sbsess"

# Inflation goes through the READ tool, one file per call.
#
# MEASURED on this box, not assumed (evidence/probe.json, evidence/probe-*.json):
# a tool result is truncated at ~30_000 characters whatever the tool. Bash is
# middle-truncated there and `BASH_MAX_OUTPUT_LENGTH` did NOT lift it on 2.1.223;
# Read has a separate 256KB file ceiling but still delivers only the first
# ~30_000 characters (a 400-line x 600-char file arrived as lines L00001-L00050
# with a truncation notice). So each filler file sits just UNDER that cap and
# arrives whole, and the token budget is made up of call COUNT rather than
# file size.
#
# Filler is high-entropy printable ASCII with no word structure, so byte-pair
# merges mostly fail and the text costs roughly 1.5-2.5 characters per token --
# the opposite of prose. Even at a pessimistic 4 chars/token the budget below
# clears HARD.
#
# claude-sonnet-5's HARD cap is 150_000 ABSOLUTE tokens against a 1_000_000
# window (read from scripts/gauge_reader.py _PROFILES, not assumed):
#
#   24 calls x 28_000 chars = 672_000 chars
#     pessimistic 4.0 chars/token -> ~168_000 tokens  (over HARD)
#     likely      2.5 chars/token -> ~269_000 tokens
#     dense       1.5 chars/token -> ~448_000 tokens  (still < window)
#
# Every case lands over HARD and none approaches the 1M window, so
# auto-compaction cannot reset the reading mid-protocol.
FILLER_CHARS = 28_000
FILLER_COUNT = 24
FILLER_LINE_CHARS = 200

# Per-arm wall-clock bound. A headless run that has not finished by then is
# killed and reported as such rather than hanging the gate.
ARM_TIMEOUT_S = 3600
PROBE_TIMEOUT_S = 300


def log(msg: str) -> None:
    print("[{0}] {1}".format(datetime.now().strftime("%H:%M:%S"), msg), flush=True)


def run(cmd, cwd=None, env=None, timeout=None, capture=True):
    return subprocess.run(
        cmd, cwd=str(cwd) if cwd else None, env=env, timeout=timeout,
        capture_output=capture, text=True, encoding="utf-8", errors="replace",
    )


def _force_rm(path: Path) -> None:
    """rmtree that survives git's read-only pack files on Windows."""
    def onerror(func, p, exc):
        try:
            os.chmod(p, 0o700)
            func(p)
        except Exception:
            pass
    if path.exists():
        shutil.rmtree(path, onexc=onerror)
    if path.exists():                       # last resort
        run(["cmd", "/c", "rmdir", "/s", "/q", str(path)])


def sha256(path: Path) -> str | None:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return None


# --------------------------------------------------------------------------- #
# arm trees -- a COMPLETE scripts/ tree each
# --------------------------------------------------------------------------- #

def build_arms() -> dict:
    """Two complete `scripts/` trees. Treatment = this worktree's current
    scripts/; control = `git archive <BASE_COMMIT>`.

    COMPLETE, not two files: gauge_writer_hook.py imports spine_rail.py as a
    FILESYSTEM SIBLING and, if the sibling set is incomplete, writes NOTHING,
    SILENTLY -- which would look exactly like the bug reproducing.
    """
    arms = TMP / "arms"
    _force_rm(arms)
    treatment = arms / "treatment"
    control = arms / "control"
    treatment.mkdir(parents=True)
    control.mkdir(parents=True)

    shutil.copytree(REPO / "scripts", treatment / "scripts",
                    ignore=shutil.ignore_patterns("__pycache__"))

    tar = control / "control.tar"
    with open(tar, "wb") as fh:
        proc = subprocess.run(["git", "archive", BASE_COMMIT, "scripts"],
                              cwd=str(REPO), stdout=fh)
    if proc.returncode != 0:
        raise SystemExit("git archive {0} failed".format(BASE_COMMIT))
    r = run(["tar", "-xf", str(tar)], cwd=control)
    if r.returncode != 0:
        raise SystemExit("tar extract failed: " + (r.stderr or ""))
    tar.unlink()

    return {"treatment": treatment, "control": control}


def arm_diff(arms: dict) -> str:
    """Recursive diff of the two arm trees. Load-bearing evidence: it is what
    proves the arms differ ONLY in scripts/hooks/spine_rail.py."""
    r = run(["diff", "-rq", str(arms["control"] / "scripts"),
             str(arms["treatment"] / "scripts")])
    return r.stdout or ""


def build_settings(arms: dict) -> dict:
    """One settings file per arm. The hooks are wired BY ABSOLUTE PATH into that
    arm's own tree, `spine_rail.py` AHEAD of `gauge_writer_hook.py`.

    Everything except the two absolute paths is generated identically for both
    arms from this one function -- that is the whole experimental control.
    """
    out = {}
    sdir = TMP / "settings"
    sdir.mkdir(parents=True, exist_ok=True)
    for name, root in arms.items():
        hooks_dir = root / "scripts" / "hooks"
        settings = {
            "env": {
                # Identical in both arms. Measured NOT to lift the Bash
                # truncation ceiling on 2.1.223 (evidence/probe.json) -- kept
                # only so the two settings files stay generated by one code
                # path. Inflation goes through Read, which is not capped here.
                "BASH_MAX_OUTPUT_LENGTH": str(FILLER_CHARS + 50_000),
            },
            "permissions": {"allow": ["Bash", "Read", "Write", "Edit", "Task", "Glob", "Grep"]},
            "hooks": {
                "PostToolUse": [
                    {"matcher": "Bash", "hooks": [{
                        "type": "command",
                        "command": 'py "{0}" PostToolUse'.format(
                            (hooks_dir / "spine_rail.py").as_posix()),
                        "timeout": 15,
                    }]},
                    {"matcher": "*", "hooks": [{
                        "type": "command",
                        "command": 'py "{0}"'.format(
                            (hooks_dir / "gauge_writer_hook.py").as_posix()),
                        "timeout": 15,
                    }]},
                ]
            },
        }
        path = sdir / "{0}.json".format(name)
        path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        out[name] = path
    return out


# --------------------------------------------------------------------------- #
# sandbox pair -- one fresh pair per arm, built by the same code
# --------------------------------------------------------------------------- #

SPINE = {
    "work_id": WORK_ID,
    "type": "gated",
    "config_ref": "docs/agents/engine-config.json",
    "items": ["m1", "m2"],
    "tasks": {
        "m1": {
            "id": "m1", "title": "sandbox step one",
            "imperative": "sandbox step one",
            "preconditions": [],
            "postconditions": [{"id": "c1", "statement": "sandbox step one done",
                                "check": None, "satisfied": True}],
            "constraints": [], "directives": None, "child_checklist": None,
            "status": "pending", "status_detail": {}, "result": None,
            "finding": None, "evidence": [], "rework_count": 0,
        },
        "m2": {
            "id": "m2", "title": "sandbox step two",
            "imperative": "sandbox step two",
            "preconditions": [],
            "postconditions": [{"id": "c1", "statement": "sandbox step two done",
                                "check": None, "satisfied": True}],
            "constraints": [], "directives": None, "child_checklist": None,
            "status": "pending", "status_detail": {}, "result": None,
            "finding": None, "evidence": [], "rework_count": 0,
        },
    },
    "consolidation": None, "triage_candidates": [], "blockers": [],
}


# A launcher that puts the ENGINE PROCESS's working directory in the worktree,
# which is what a shell already resident in a worktree gives for free. It exists
# because a headless subagent's Bash tool resets its cwd between calls, so the
# only other way to make a relative `--file` resolve would be a `cd` in the
# observed command -- and the hook PARSES a `cd` target as a candidate root.
#
# THIS IS THE POINT: with no `cd`, the harness places the worktree root in NO
# field the hook reads (not `--file`, not `--worktree`, not a `cd` target, not
# the payload `cwd`, not an environment variable). The hook must DERIVE the
# worktree by shelling out to `git worktree list` -- rung 4, `path_source:
# git_worktree` -- or bind nothing. The shim's own path appears in the command
# text only as the script token, which the resolution never treats as a root.
#
# It derives its own root from __file__ and forwards argv unchanged, so it adds
# no argument the hook could read and preserves the engine's real exit code.
SHIM = '''import os, subprocess, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.exit(subprocess.run(
    [sys.executable, os.path.join(root, "scripts", "checklist_engine.py")] + sys.argv[1:],
    cwd=root).returncode)
'''


def make_filler(dest: Path, count: int) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    rnd = random.Random(4400)
    alphabet = ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
                "+/=!@#$%^&*()[]{}<>?;:,.~|")
    for i in range(1, count + 1):
        # Line-shaped so the Read tool's 2000-char per-line truncation never
        # applies, and sized under the ~30_000-char tool-output cap so the whole
        # file arrives with no truncation notice.
        lines = []
        while sum(len(x) + 1 for x in lines) < FILLER_CHARS:
            lines.append("".join(rnd.choice(alphabet) for _ in range(FILLER_LINE_CHARS)))
        (dest / "f{0:02d}.txt".format(i)).write_text("\n".join(lines), encoding="utf-8")


def build_sandbox(arm: str, filler_count: int) -> dict:
    """A scratch `git init` main plus a REAL `git worktree add` of it.

    The spine is created ONLY in the worktree and is never committed, so the
    same relative path does not exist in the sandbox main. The hook is told
    nothing about where it is.
    """
    root = TMP / "run-{0}".format(arm)
    _force_rm(root)
    main = root / "main"
    wt = root / "wt"
    main.mkdir(parents=True)

    # The engine and its ONE sibling import. No hooks live in the sandbox at
    # all, so there is no chance the sandbox's own copy is the code under test.
    (main / "scripts").mkdir()
    for f in ("checklist_engine.py", "gauge_reader.py"):
        shutil.copy2(REPO / "scripts" / f, main / "scripts" / f)
    # No engine-config.json is shipped: this repo has none either, so
    # `load_config` resolves to {} and the engine runs on its defaults --
    # exactly as it does on every real run here.

    for cmd in (["git", "init", "-q", "-b", "main"],
                ["git", "config", "user.email", "sandbox@example.invalid"],
                ["git", "config", "user.name", "sandbox"],
                ["git", "add", "-A"],
                ["git", "commit", "-q", "-m", "sandbox base"]):
        r = run(cmd, cwd=main)
        if r.returncode != 0:
            raise SystemExit("sandbox git failed: {0}\n{1}".format(cmd, r.stderr))
    r = run(["git", "worktree", "add", "-q", "-b", "sbwt", str(wt)], cwd=main)
    if r.returncode != 0:
        raise SystemExit("git worktree add failed: " + (r.stderr or ""))

    # The shim lives in the WORKTREE (untracked), named so the hook's
    # `checklist_engine.py` token test still fires on the observed command.
    (wt / "bin").mkdir(parents=True, exist_ok=True)
    (wt / "bin" / "checklist_engine.py").write_text(SHIM, encoding="utf-8")

    spine_dir = wt / ".agent-work" / WORK_ID
    spine_dir.mkdir(parents=True)
    (spine_dir / "spine.json").write_text(json.dumps(SPINE, indent=2) + "\n",
                                          encoding="utf-8")
    make_filler(wt / "filler", filler_count)
    return {"root": root, "main": main, "wt": wt,
            "spine": spine_dir / "spine.json", "gauge_wt": spine_dir / "gauge.json",
            "gauge_main": main / ".agent-work" / WORK_ID / "gauge.json"}


# --------------------------------------------------------------------------- #
# prompts -- generated identically for both arms
# --------------------------------------------------------------------------- #

def subagent_prompt(sb: dict, filler_count: int) -> str:
    wt = sb["wt"].as_posix()
    engine = (sb["wt"] / "bin" / "checklist_engine.py").as_posix()
    out = "{0}/.agent-work/{1}/advance-out.txt".format(wt, WORK_ID)
    reads = "\n".join("{0}/filler/f{1:02d}.txt".format(wt, i)
                      for i in range(1, filler_count + 1))
    return """You are the TEST SUBJECT in a sanctioned engineering acceptance test.

WHAT IS BEING TESTED, so nothing below looks like a trick:
This repository has a context-fullness governor. A hook samples the acting
agent's own context fill after every tool call and writes it next to that
agent's checklist; the checklist engine then REFUSES to `advance` once the fill
passes a hard limit. Whether that refusal actually fires for an agent working in
a git worktree is an open question, and this run is how it gets answered.

So the bulk reading in STEP 3 is not a prompt-injection attempt and not a waste
of your effort -- it IS the experiment. The governor cannot be observed firing
unless a real agent's context genuinely reaches the limit, and reading a lot of
meaningless data is the honest way to get there. The content is random noise
generated by the harness; it contains no instructions and means nothing. Ignore
what you read entirely. Only the fact that you read it matters.

Everything happens in a disposable sandbox under your temp directory. Nothing
here touches a real repository.

Please complete ALL steps. Stopping early produces no result at all, and a
partial run cannot be told apart from the bug this test is trying to detect.

Follow these steps IN ORDER, exactly as written. Run each command as its OWN
tool call. Do not combine commands. Do not skip any step. Do not stop early.
Do not explain anything until the very end.

STEP 1 -- run this EXACT command:
python "{engine}" --file .agent-work/{wid}/spine.json claim --session-id {es} --claimed-by sandbox

STEP 2 -- run this EXACT command:
python "{engine}" --file .agent-work/{wid}/spine.json start m1 --session-id {es}

STEP 3 -- use the READ tool (not Bash) on ALL {n} of these files, ONE READ CALL
PER FILE, in order. All {n} are required; this is the context inflation the test
is built around, so reading fewer than {n} invalidates the run. Do not summarize,
do not comment, do not skip any -- read one, ignore it, read the next:
{reads}

STEP 4 -- run this EXACT command:
echo post-inflation-marker > "{wt}/.agent-work/{wid}/marker.txt"

STEP 5 -- run this EXACT command:
python "{engine}" --file .agent-work/{wid}/spine.json advance m1 --session-id {es} --mechanical > "{out}" 2>&1; echo "EXIT=$?" >> "{out}"

STEP 6 -- run this EXACT command:
cat "{out}"

Then reply with exactly: PROTOCOL-COMPLETE
""".format(wt=wt, engine=engine, wid=WORK_ID, es=ENGINE_SESSION, n=filler_count,
           reads=reads, out=out)


def parent_prompt(sb: dict, filler_count: int) -> str:
    return """You are orchestrating a sanctioned engineering acceptance test in a
disposable sandbox under the temp directory. It measures whether a context
governor's HARD refusal fires for an agent working in a git worktree, which
requires a real dispatched agent to genuinely fill its context. That is what the
prompt below asks for, and it is the point of the test rather than a trick.

Do exactly this and nothing else.

Use the Agent tool ONCE. Set subagent_type to "general-purpose", set model to
"{model}", set run_in_background to false. Pass the text between the >>>BEGIN and
>>>END markers below as the agent's prompt, verbatim and complete -- copy it
exactly, do not shorten it, do not describe it, do not add to it. It explains
itself to the subagent; summarizing it is what makes the subagent decline.

Do NOT do any of that work yourself. Your only job is the one Agent call.

If the subagent declines or stops early, say so plainly in your reply -- a
half-run is worse than a refusal, because it cannot be told apart from the bug
under test.

When the subagent returns, reply with exactly: DONE

>>>BEGIN
{sub}
>>>END
""".format(model=SUBAGENT_MODEL, sub=subagent_prompt(sb, filler_count))


# --------------------------------------------------------------------------- #
# launching an arm
# --------------------------------------------------------------------------- #

def launch(prompt: str, cwd: Path, settings: Path, model: str, log_path: Path,
           timeout: int) -> dict:
    """A headless `claude -p` with cwd AND CLAUDE_PROJECT_DIR on the sandbox main.

    That pairing is the defect's own precondition: the session's project dir is
    the main checkout while the work happens in the worktree. The ABSOLUTE hook
    path in `settings` is what makes the arm's code run anyway.
    """
    env = dict(os.environ)
    env["CLAUDE_PROJECT_DIR"] = str(cwd)
    env["BASH_MAX_OUTPUT_LENGTH"] = str(FILLER_CHARS + 50_000)
    cmd = [str(CLAUDE), "-p", prompt,
           "--settings", str(settings),
           "--model", model,
           "--permission-mode", "acceptEdits",
           "--add-dir", str(cwd.parent)]
    started = time.time()
    timed_out = False
    try:
        r = run(cmd, cwd=cwd, env=env, timeout=timeout)
        out, err, rc = r.stdout, r.stderr, r.returncode
    except subprocess.TimeoutExpired as exc:
        timed_out = True
        out = (exc.stdout or b"").decode("utf-8", "replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        err = (exc.stderr or b"").decode("utf-8", "replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        rc = None
    elapsed = time.time() - started
    log_path.write_text(
        "CMD: {0}\nCWD: {1}\nCLAUDE_PROJECT_DIR: {1}\nEXIT: {2}\nTIMED_OUT: {3}\n"
        "ELAPSED_S: {4:.1f}\n\n--- STDOUT ---\n{5}\n--- STDERR ---\n{6}\n".format(
            " ".join(cmd[:1] + ["-p", "<prompt>"] + cmd[3:]), cwd, rc, timed_out,
            elapsed, out, err),
        encoding="utf-8")
    return {"exit": rc, "timed_out": timed_out, "elapsed_s": round(elapsed, 1),
            "stdout": out, "stderr": err}


# --------------------------------------------------------------------------- #
# preflight -- the arm trees are COMPLETE and each resolves the way it should
# --------------------------------------------------------------------------- #

def preflight(arms: dict) -> dict:
    """Drive each arm's spine_rail.py directly, once, on a synthetic payload.

    CONFIRMATORY ONLY -- it is not the acceptance and proves nothing about a
    live trip. What it buys is worth having before an hour of headless time:

    1. The arm tree is COMPLETE. An incomplete sibling set makes the gauge
       writer fail its `spine_rail.py` import and write NOTHING, SILENTLY --
       indistinguishable from the bug reproducing.
    2. Each arm resolves the way the fix says it does, and names WHICH RUNG did
       it. The treatment arm must report `path_source: git_worktree` -- derived
       by shelling out to `git worktree list`, not read from anything the
       harness handed it.
    """
    out = {}
    for arm in ("treatment", "control"):
        sb = build_sandbox("pf-" + arm, 1)
        shim = (sb["wt"] / "bin" / "checklist_engine.py").as_posix()
        cmd = ('python "{0}" --file .agent-work/{1}/spine.json claim '
               '--session-id {2} --claimed-by sandbox').format(shim, WORK_ID, ENGINE_SESSION)
        drive = subprocess.run(cmd, shell=True, cwd=str(sb["main"]),
                               capture_output=True, text=True)
        payload = {"session_id": "PFSESSION", "agent_id": "pfagent0001",
                   "cwd": str(sb["main"]), "transcript_path": "absent",
                   "tool_name": "Bash", "tool_input": {"command": cmd}}
        env = dict(os.environ)
        env["CLAUDE_PROJECT_DIR"] = str(sb["main"])
        hook = str(arms[arm] / "scripts" / "hooks" / "spine_rail.py")
        h = subprocess.run(["python", hook, "PostToolUse"], input=json.dumps(payload),
                           text=True, capture_output=True, env=env)
        store = read_json(sb["main"] / ".agent-work" / ".spine-rail-binding.json")
        entry = None
        for val in (store or {}).values():
            for spine_path, e in (val or {}).items():
                entry = {"spine": spine_path, "path_source": (e or {}).get("path_source")}
        out[arm] = {
            "observed_command": cmd,
            "engine_drove_ok": drive.returncode == 0,
            "hook_exit": h.returncode,
            "hook_stderr": (h.stderr or "")[:400],
            "binding_store": store,
            "resolved": entry,
            "spine_really_at": str(sb["spine"]),
            "spine_present_in_sandbox_main": (
                sb["main"] / ".agent-work" / WORK_ID / "spine.json").exists(),
        }
        _force_rm(sb["root"])
    (EVIDENCE / "preflight-arms.json").write_text(json.dumps(out, indent=2),
                                                  encoding="utf-8")
    return out


# --------------------------------------------------------------------------- #
# probe -- is a whole filler file delivered, or middle-truncated?
# --------------------------------------------------------------------------- #

def probe(settings: Path) -> int:
    """Confirm a whole filler file survives ONE Read call.

    A truncated tool result would silently shrink the inflation and could leave
    the subagent under the HARD cap -- a false negative wearing the bug's face.
    Returns the filler count to use; a TRUNCATED verdict is reported, not
    silently worked around.
    """
    root = TMP / "probe"
    _force_rm(root)
    root.mkdir(parents=True)
    make_filler(root / "filler", 1)
    prompt = ("Run this exact Bash command as one tool call:\n"
              'cat "{0}/filler/f01.txt"\n'
              "Then look at the tool result YOU received. If it contains any "
              "truncation marker or notice saying content was omitted or "
              "truncated, reply with exactly TRUNCATED. Otherwise reply with "
              "exactly FULL. Reply with that one word only.").format(
                  (root / "filler").parent.as_posix())
    res = launch(prompt, root, settings, PARENT_MODEL,
                 TMP / "logs" / "probe.log", PROBE_TIMEOUT_S)
    verdict = "TRUNCATED" if "TRUNCATED" in (res["stdout"] or "").upper() else (
        "FULL" if "FULL" in (res["stdout"] or "").upper() else "UNKNOWN")
    log("probe verdict: {0} (exit {1})".format(verdict, res["exit"]))
    (EVIDENCE / "probe.json").write_text(json.dumps({
        "filler_chars": FILLER_CHARS, "verdict": verdict,
        "exit": res["exit"], "stdout": (res["stdout"] or "")[:2000],
    }, indent=2), encoding="utf-8")
    _force_rm(root)
    # FULL: 6 x 200_000 chars ~ 400K tokens. Otherwise assume ~30_000 chars per
    # call survives and take 30 calls to reach a comparable budget.
    return FILLER_COUNT


# --------------------------------------------------------------------------- #
# evidence collection
# --------------------------------------------------------------------------- #

def read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def transcript_diagnostics(sb: dict) -> dict:
    """Where the harness's own session transcript landed, and whether the
    dispatched agent's derived transcript is on disk beside it.

    This is the diagnostic for `docs/GAUGE_WRITER_HOOK.md` "Skip-on-uncertainty,
    enumerated": a missing `subagents/agent-<id>.jsonl` is the
    `subagent-transcript-missing` cause, and a missing session transcript
    entirely is the silent `transcript_path` cause. Without this, a quiet writer
    cannot be told apart from the bug.
    """
    try:
        projects = Path.home() / ".claude" / "projects"
        slug_key = str(sb["main"]).replace(":", "").replace("\\", "-").replace("/", "-")
        cands = [d for d in projects.iterdir()
                 if d.is_dir() and slug_key.lower().lstrip("-") in d.name.lower().lstrip("-")]
        out = []
        for d in cands:
            for jsonl in sorted(d.glob("*.jsonl"), key=lambda p: p.stat().st_mtime,
                                reverse=True)[:3]:
                subs = jsonl.with_suffix("") / "subagents"
                out.append({
                    "session_transcript": str(jsonl),
                    "size": jsonl.stat().st_size,
                    "subagents_dir": str(subs),
                    "subagents_dir_exists": subs.is_dir(),
                    "subagent_transcripts": sorted(p.name for p in subs.glob("*.jsonl"))
                    if subs.is_dir() else [],
                })
        return {"projects_root": str(projects), "slug_key": slug_key,
                "matched_dirs": [str(d) for d in cands], "sessions": out}
    except Exception as exc:
        return {"error": repr(exc)}


def collect(arm: str, sb: dict, res: dict, hook_path: str) -> dict:
    """Everything the verdict rests on, from disk, after the arm has run."""
    store_path = sb["main"] / ".agent-work" / ".spine-rail-binding.json"
    store = read_json(store_path)
    advance_out = sb["spine"].parent / "advance-out.txt"
    adv_text = ""
    adv_exit = None
    if advance_out.exists():
        adv_text = advance_out.read_text(encoding="utf-8", errors="replace")
        for line in adv_text.splitlines():
            if line.startswith("EXIT="):
                try:
                    adv_exit = int(line.split("=", 1)[1].strip())
                except ValueError:
                    pass

    # Attribution: composite key shape, identity_resolution_ms, model.
    composite_keys = []
    entries = []
    if isinstance(store, dict):
        for key, val in store.items():
            if "#" in key:
                composite_keys.append(key)
            if isinstance(val, dict):
                for spine_path, entry in val.items():
                    entries.append({"key": key, "spine": spine_path,
                                    "path_source": (entry or {}).get("path_source"),
                                    "worktree": (entry or {}).get("worktree")})

    gauge_wt = read_json(sb["gauge_wt"])
    gauge_main = read_json(sb["gauge_main"])
    reading = gauge_wt if gauge_wt else gauge_main

    spine_state = read_json(sb["spine"]) or {}
    m1_status = ((spine_state.get("tasks") or {}).get("m1") or {}).get("status")

    return {
        "arm": arm,
        "collected_at": datetime.now(timezone.utc).isoformat(),
        "hook_path": hook_path,
        "parent_model": PARENT_MODEL,
        "subagent_model_requested": SUBAGENT_MODEL,
        "sandbox": {"main": str(sb["main"]), "wt": str(sb["wt"]),
                    "spine": str(sb["spine"])},
        "headless": {"exit": res["exit"], "timed_out": res["timed_out"],
                     "elapsed_s": res["elapsed_s"],
                     "stdout_tail": (res["stdout"] or "")[-1500:]},
        "binding_store_path": str(store_path),
        "binding_store": store,
        "binding_entries": entries,
        "composite_keys": composite_keys,
        "gauge_in_worktree": {"path": str(sb["gauge_wt"]),
                              "exists": sb["gauge_wt"].exists(),
                              "record": gauge_wt},
        "gauge_in_main_phantom": {"path": str(sb["gauge_main"]),
                                  "exists": sb["gauge_main"].exists(),
                                  "record": gauge_main},
        "skip_sidecar_wt": read_json(sb["gauge_wt"].with_name("gauge-skip.json")),
        "skip_sidecar_main": read_json(sb["gauge_main"].with_name("gauge-skip.json")),
        "uncalibrated_wt": read_json(sb["gauge_wt"].with_name("gauge-uncalibrated.json")),
        "transcript_diagnostics": transcript_diagnostics(sb),
        "advance_output": adv_text,
        "advance_exit": adv_exit,
        "m1_status_after": m1_status,
        "attribution": {
            "composite_key_present": bool(composite_keys),
            "identity_resolution_ms": (reading or {}).get("identity_resolution_ms"),
            "gauge_model": (reading or {}).get("model"),
            "subagent_model_id_expected": SUBAGENT_MODEL_ID,
            "fill_fraction": (reading or {}).get("fill_fraction"),
            "observed_at": (reading or {}).get("observed_at"),
            "wall_clock_at_collect": datetime.now(timezone.utc).isoformat(),
        },
    }


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #

def real_store_fingerprint() -> dict:
    """The LIVE main checkout's binding store, hashed before and after. A live
    Admiral session is using it; the harness must never write it."""
    p = Path("C:/Programs/constellation-skills/.agent-work/.spine-rail-binding.json")
    return {"path": str(p), "sha256": sha256(p),
            "size": p.stat().st_size if p.exists() else None}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep", action="store_true", help="leave the temp tree in place")
    ap.add_argument("--probe-only", action="store_true")
    ap.add_argument("--preflight-only", action="store_true")
    ap.add_argument("--arm", choices=["treatment", "control"],
                    help="run only this arm")
    ap.add_argument("--filler-count", type=int, default=None)
    args = ap.parse_args()

    EVIDENCE.mkdir(parents=True, exist_ok=True)
    (TMP / "logs").mkdir(parents=True, exist_ok=True)

    before = real_store_fingerprint()

    log("building arm trees")
    arms = build_arms()
    diff_text = arm_diff(arms)
    (EVIDENCE / "arm-diff.txt").write_text(
        "# recursive diff: control (cbd9aee) vs treatment (HEAD), full scripts/ trees\n"
        "# command: diff -rq <control>/scripts <treatment>/scripts\n\n"
        + (diff_text or "(no differences)\n"), encoding="utf-8")
    log("arm diff:\n" + diff_text)

    settings = build_settings(arms)
    for name, path in settings.items():
        shutil.copy2(path, EVIDENCE / "settings-{0}.json".format(name))

    log("preflight: arm trees complete, resolution rung per arm")
    pf = preflight(arms)
    for arm, d in pf.items():
        log("  {0}: hook_exit={1} resolved={2}".format(arm, d["hook_exit"], d["resolved"]))
    if args.preflight_only:
        return 0

    if args.filler_count is not None:
        filler_count = args.filler_count
    else:
        log("probing tool-output truncation")
        filler_count = probe(settings["treatment"])
    log("filler count = {0} x {1} chars".format(filler_count, FILLER_CHARS))
    if args.probe_only:
        return 0

    which = [args.arm] if args.arm else ["treatment", "control"]
    for arm in which:
        log("=== ARM {0}: building sandbox ===".format(arm))
        sb = build_sandbox(arm, filler_count)
        prompt = parent_prompt(sb, filler_count)
        (EVIDENCE / "prompt-{0}.txt".format(arm)).write_text(prompt, encoding="utf-8")
        hook_path = (arms[arm] / "scripts" / "hooks" / "spine_rail.py").as_posix()
        log("=== ARM {0}: launching headless run (hooks -> {1}) ===".format(arm, hook_path))
        res = launch(prompt, sb["main"], settings[arm], PARENT_MODEL,
                     TMP / "logs" / "{0}.log".format(arm), ARM_TIMEOUT_S)
        log("=== ARM {0}: exit={1} timed_out={2} elapsed={3}s ===".format(
            arm, res["exit"], res["timed_out"], res["elapsed_s"]))
        ev = collect(arm, sb, res, hook_path)
        (EVIDENCE / "arm-{0}.json".format(arm)).write_text(
            json.dumps(ev, indent=2), encoding="utf-8")
        shutil.copy2(TMP / "logs" / "{0}.log".format(arm),
                     EVIDENCE / "headless-{0}.log".format(arm))
        log("collected: gauge_wt={0} gauge_main={1} advance_exit={2}".format(
            ev["gauge_in_worktree"]["exists"], ev["gauge_in_main_phantom"]["exists"],
            ev["advance_exit"]))

    after = real_store_fingerprint()
    (EVIDENCE / "live-checkout-untouched.json").write_text(json.dumps({
        "before": before, "after": after,
        "unchanged": before["sha256"] == after["sha256"] and before["size"] == after["size"],
    }, indent=2), encoding="utf-8")

    if not args.keep:
        log("cleaning up {0}".format(TMP))
        _force_rm(TMP)
    return 0


if __name__ == "__main__":
    sys.exit(main())
