#!/usr/bin/env python3
"""Compare every installed skill bundle against the source it was built from.

WHY THIS EXISTS. `install_constellation.py` copies a skill's source tree into the
installed bundle and then rewrites placeholder tokens in it -- `<skill-dir>`,
`<{role}-skill-dir>`, and the `python <` interpreter prefix -- into absolute
installed paths and the interpreter probed on this host. Nothing afterwards ever
compares the copy against its source, so an installed bundle can silently lag main
while every gate reports green. Epic #418 measured that failure three times: #501
(bundle detection by name), #439/#446/#484 (`archive.c2b` check text), and an
Admiral blocked by a `spine.json` instantiated before its own repair landed.

WHY THE OBVIOUS CHECK DOESN'T WORK. Comparing source bytes to installed bytes
reports every placeholder-bearing bundle as stale. During #418's own closeout a
substitution-blind comparison flagged three current bundles as drifted; the three
were simply the ones whose SKILL.md carried placeholders. So this script applies
the installer's OWN substitution map to the source before comparing, importing
`installed_path_replacements` rather than re-deriving it -- a verifier with its own
copy of that map would drift from the installer and report its own drift as the
corpus's.

WHAT IT MODELS. `install_skills` writes a bundle in three passes, and the later
ones overwrite the earlier, so expected content is built the same way:

  1. `shutil.copytree(skill.source_path, target)` then `rewrite_installed_skill_paths`
     -- every file under `skills/<role>/`, SUBSTITUTED (only `.json`/`.md`/`.txt`;
     other suffixes are copied untouched).
  2. `required_scripts` copied flat into `<target>/scripts/` from the repo's
     top-level `scripts/` -- copied AFTER the rewrite, so byte-identical to source
     and NOT substituted, even where it lands on a path pass 1 had written.
  3. `required_references` copied into `<target>/references/` from
     `skills/_shared/` -- also after the rewrite, also byte-identical. This is why
     `skills/<role>/references/global-*.md` is an install-time copy and
     `skills/_shared/global-*.md` is the source of truth.

`interpreter.json` is generated by the installer, has no source, and is read rather
than compared.

The interpreter is read from each bundle's own `interpreter.json` sidecar rather
than re-probed, so this script reports what the bundle was actually built with and
is deterministic across hosts. A bundle with no sidecar is reported, not guessed at.

Line endings are normalised before comparison. This repo stores CRLF in the working
tree while the installer round-trips text through Python's universal newlines, and a
bare `diff` on that difference is the exact false positive that cost #418 a retracted
scope accusation.

Exit codes: 0 = every bundle matches its source. 1 = at least one difference. 2 = the
check could not run (no installed root, unreadable source).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from install_constellation import (  # noqa: E402
    AGENT_TARGETS,
    REPO_ROOT,
    REWRITABLE_TEXT_SUFFIXES,
    SHARED_REFERENCE_ROOT,
    SOURCE_ROOT,
    InterpreterResolution,
    Skill,
    apply_installed_path_replacements,
    discover_skills,
    installed_path_replacements,
    resolve_target_root,
    script_source_path,
)

SIDECAR = "interpreter.json"


def _normalise(text: str) -> str:
    """Line-ending-insensitive form. See the module docstring on why a raw
    comparison is not the honest test in this repo."""
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


@dataclass
class BundleReport:
    name: str
    target: Path
    status: str  # "in-sync" | "differs" | "missing" | "no-sidecar"
    interpreter: str | None = None
    resolved_via: str | None = None
    differing: list[str] = field(default_factory=list)
    missing_files: list[str] = field(default_factory=list)
    extra_files: list[str] = field(default_factory=list)
    binary_skipped: int = 0

    @property
    def problem_count(self) -> int:
        return len(self.differing) + len(self.missing_files) + len(self.extra_files)


def _sidecar_interpreter(target: Path) -> InterpreterResolution | None:
    raw = _read_text(target / SIDECAR)
    if raw is None:
        return None
    try:
        data = json.loads(raw)
        return InterpreterResolution(
            interpreter=str(data["interpreter"]),
            candidates=tuple(str(c) for c in data.get("candidates", ())),
            resolved_via=str(data.get("resolved_via", "unknown")),
        )
    except (json.JSONDecodeError, KeyError, TypeError):
        return None


def expected_bundle(
    skill: Skill, target: Path, interpreter: InterpreterResolution
) -> dict[str, Path | tuple[Path, bool]]:
    """Map of bundle-relative posix path -> (source path, substituted?).

    Built in the installer's own three passes, later passes overwriting earlier,
    so a `required_script` that lands on a path pass 1 also wrote is recorded as
    unsubstituted -- which is what actually ends up on disk.
    """
    expected: dict[str, tuple[Path, bool]] = {}

    for src in sorted(skill.source_path.rglob("*")):
        if not src.is_file():
            continue
        rel = src.relative_to(skill.source_path).as_posix()
        substituted = src.suffix.lower() in REWRITABLE_TEXT_SUFFIXES
        expected[rel] = (src, substituted)

    for script in skill.required_scripts:
        expected[f"scripts/{script}"] = (
            script_source_path(script, REPO_ROOT / "scripts"),
            False,
        )

    for reference in skill.required_references:
        expected[f"references/{reference}"] = (SHARED_REFERENCE_ROOT / reference, False)

    return expected


def verify_bundle(skill: Skill, target_root: Path) -> BundleReport:
    target = target_root / skill.install_name
    if not target.is_dir():
        return BundleReport(skill.install_name, target, "missing")

    interpreter = _sidecar_interpreter(target)
    if interpreter is None:
        return BundleReport(skill.install_name, target, "no-sidecar")

    report = BundleReport(
        skill.install_name,
        target,
        "in-sync",
        interpreter=interpreter.interpreter,
        resolved_via=interpreter.resolved_via,
    )
    replacements = installed_path_replacements(target, skill, interpreter)
    expected = expected_bundle(skill, target, interpreter)

    for rel, (src, substituted) in sorted(expected.items()):
        installed = target / rel
        if not installed.is_file():
            report.missing_files.append(rel)
            continue
        source_text = _read_text(src)
        installed_text = _read_text(installed)
        if source_text is None or installed_text is None:
            # Binary or unreadable: compare bytes instead of pretending to diff text.
            report.binary_skipped += 1
            try:
                if src.read_bytes() != installed.read_bytes():
                    report.differing.append(rel)
            except OSError:
                report.differing.append(rel)
            continue
        want = apply_installed_path_replacements(source_text, replacements) if substituted else source_text
        if _normalise(want) != _normalise(installed_text):
            report.differing.append(rel)

    for path in sorted(target.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(target).as_posix()
        if rel == SIDECAR or rel in expected:
            continue
        report.extra_files.append(rel)

    if report.problem_count:
        report.status = "differs"
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--agent", default="claude", choices=sorted(AGENT_TARGETS))
    parser.add_argument("--scope", default="user", choices=("user", "project"))
    parser.add_argument("--project", type=Path, default=None)
    parser.add_argument(
        "--skills-root",
        type=Path,
        default=None,
        help="verify this installed root directly, bypassing --agent/--scope resolution",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable report")
    args = parser.parse_args(argv)

    if args.skills_root is not None:
        target_root = args.skills_root
    else:
        # resolve_target_root reads a Namespace, so hand it one rather than
        # reimplementing its scope/dest/project precedence here.
        try:
            target_root = resolve_target_root(
                argparse.Namespace(scope=args.scope, project=args.project, dest=None),
                AGENT_TARGETS[args.agent],
                os.environ,
                Path.cwd(),
            )
        except Exception as exc:  # noqa: BLE001 - report, never traceback
            print(f"cannot resolve installed root: {exc}", file=sys.stderr)
            return 2

    if not Path(target_root).is_dir():
        print(f"installed root does not exist: {target_root}", file=sys.stderr)
        return 2

    try:
        skills = discover_skills(SOURCE_ROOT)
    except Exception as exc:  # noqa: BLE001
        print(f"cannot read source skills: {exc}", file=sys.stderr)
        return 2

    reports = [verify_bundle(skill, Path(target_root)) for skill in skills]
    bad = [r for r in reports if r.status != "in-sync"]

    if args.json:
        print(
            json.dumps(
                {
                    "skills_root": str(target_root),
                    "bundles": [
                        {
                            "name": r.name,
                            "status": r.status,
                            "interpreter": r.interpreter,
                            "resolved_via": r.resolved_via,
                            "differing": r.differing,
                            "missing": r.missing_files,
                            "extra": r.extra_files,
                        }
                        for r in reports
                    ],
                },
                indent=2,
            )
        )
        return 1 if bad else 0

    print(f"installed bundle verification against source: {target_root}")
    print(f"  compared {len(reports)} bundle(s) from {SOURCE_ROOT}")
    for r in reports:
        if r.status == "in-sync":
            continue
        print(f"  {r.name}: {r.status.upper()}")
        for rel in r.differing:
            print(f"      differs: {rel}")
        for rel in r.missing_files:
            print(f"      missing from bundle: {rel}")
        for rel in r.extra_files:
            print(f"      not from any source: {rel}")
    if not bad:
        interpreters = {r.interpreter for r in reports if r.interpreter}
        print(f"  every bundle matches its source (interpreter: {', '.join(sorted(interpreters))})")
        print("  Substitution-aware: placeholder tokens were resolved from each bundle's own")
        print("  interpreter.json before comparing, so a substituted file is not read as drift.")
        return 0
    print(f"  {len(bad)} bundle(s) do not match source. Re-run install_constellation.py --force.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
